const EVENTS = {
  connection: "connection",
  CLIENT: {
    CREATE_ROOM: "CREATE_ROOM",
    CEREATE_PRIVATE_CHAT: "CEREATE_PRIVATE_CHAT",
    SEND_ROOM_MESSAGE: "SEND_ROOM_MESSAGE",
    SEND_PRIVATE_MESSAGE: "SEND_PRIVATE_MESSAGE",
    JOIN_PRIVATE_CHAT: "JOIN_PRIVATE_CHAT",
    JOINED_ROOM: "JOINED_ROOM",
    AUTH: {
      LOGIN: "LOGIN",
      SIGNUP: "SIGNUP",
      SUCCESS: "SUCCESS",
      ERROR: "ERROR",
      SENDBACK_JWT_COOKIE: "SENDBACK_JWT_COOKIE",
    },
  },
  SERVER: {
    ROOMS: "ROOMS",
    MY_ROOMS: "MY_ROOMS",
    JOINED_ROOM: "JOINED_ROOM",
    ROOM_MESSAGE: "ROOM_MESSAGE",
    PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
    JOIN_PRIVATE_CHAT: "JOIN_PRIVATE_CHAT",
    AUTH: {
      LOGIN: "LOGIN",
      SIGNUP: "SIGNUP",
      SUCCESS: "SUCCESS",
      ERROR: "ERROR",
      SENDBACK_JWT_COOKIE: "SENDBACK_JWT_COOKIE",
    },
  },
};

module.exports = EVENTS;
